### ISSUE TITLE
Fullbright Bug

### ISSUE THREAD

**Issue by KiraRevenant** [TerraHax/TerraHax-Bin#18]
![terrariabug](https://user-images.githubusercontent.com/52699940/99883955-3b9c8600-2c33-11eb-9d63-168bca1522dc.png)
there is this bug when you activate fullbright

**Comment by AlexMarshall123** [comment]
This bug is known, it's stated under known bugs.

**Comment by KiraRevenant** [comment]
> This bug is known, it's stated under known bugs.

Oh alright. Where are the known bugs? I'm new to github

**Comment by KiraRevenant** [comment]
This bug is known sorry for not noticing.
