### ISSUE TITLE
Game updated to 1.4.0.5

### ISSUE THREAD

**Issue by Boii1** [TerraHax/TerraHax-Bin#5]

**Comment by TerraHax** [comment]
@Boii1 
I just downloaded the game again on steam to refresh the installation. Im still showing 1.4.0.4. Was there another hot fix of sorts that didn't increase the version?

**Comment by SHACKTINGG** [comment]
> @Boii1
> I just downloaded the game again on steam to refresh the installation. Im still showing 1.4.0.4. Was there another hot fix of sorts that didn't increase the version?

The game is now officially 1.4.0.5 so TerraHax no longer functions properly.

**Comment by moxpyn** [comment]
I checked, The game updated to 1.4.0.5

**Comment by anna9905** [comment]
HI
when will the **updates?**

**Comment by anna9905** [comment]
and I want to recommend adding a couple of functions
1) catching boxes
2) auto fishing
3)Full Map Render

**Comment by TerraHax** [comment]
Pushing out an update on this today.

**Comment by anna9905** [comment]
terrahax is the best 
I want to help the author very much

**Comment by TerraHax** [comment]
Updated to 1.4.0.5. Closing Issue. Report any problems found
